import React,{useState,useRef,useEffect}from'react';import{createRoot}from'react-dom/client';import{ChevronLeft,Home,Volume1,Volume2,VolumeX,MousePointer2,Keyboard,Hash,Send,Check,Tv,Wifi,X,Plus}from'lucide-react';import'./styles.css';
const RU=[['й','ц','у','к','е','н','г','ш','щ','з','х'],['ф','ы','в','а','п','р','о','л','д','ж','э'],['я','ч','с','м','и','т','ь','б','ю','.','⌫']],EN=[['q','w','e','r','t','y','u','i','o','p'],['a','s','d','f','g','h','j','k','l'],['z','x','c','v','b','n','m','.','⌫']];
const key=()=>crypto.randomUUID();
const LP_MS=500;
function useLongPress(onClick,onLongPress){let timer=useRef(null),fired=useRef(false);let start=e=>{e.preventDefault?.();fired.current=false;timer.current=setTimeout(()=>{fired.current=true;onLongPress&&onLongPress()},LP_MS)};let clear=()=>clearTimeout(timer.current);let end=()=>{clear();if(!fired.current)onClick&&onClick()};return{onPointerDown:start,onPointerUp:end,onPointerLeave:clear,onPointerCancel:clear}}
function useTouchpad(c){let last=useRef(null),moved=useRef(false);let onDown=e=>{last.current={x:e.clientX,y:e.clientY};moved.current=false;e.currentTarget.setPointerCapture?.(e.pointerId)};let onMove=e=>{if(!last.current)return;let dx=e.clientX-last.current.x,dy=e.clientY-last.current.y;if(Math.abs(dx)>2||Math.abs(dy)>2)moved.current=true;last.current={x:e.clientX,y:e.clientY};c?.move(dx,dy)};let onUp=()=>{if(last.current&&!moved.current)c?.click();last.current=null};return{onPointerDown:onDown,onPointerMove:onMove,onPointerUp:onUp,onPointerCancel:()=>{last.current=null},style:{touchAction:'none'}}}
class LG{constructor(ip,ck){this.ip=ip;this.ck=ck;this.ws=null;this.ptr=null;this.pending=new Map()}connect(onPrompt){return new Promise((ok,bad)=>{let w=this.ws=new WebSocket(`ws://${this.ip}:3000`);let to=setTimeout(()=>{w.close();bad(Error('Тайм-аут: ТВ не ответил за 60 секунд'))},60000);w.onopen=()=>w.send(JSON.stringify({type:'register',id:key(),payload:{manifest:{manifestVersion:1,appVersion:'0.1.0',permissions:['CONTROL_AUDIO','CONTROL_INPUT_JOYSTICK','CONTROL_MOUSE_AND_KEYBOARD','READ_CURRENT_CHANNEL','LAUNCH']},...(this.ck?{clientKey:this.ck}:{})}}));w.onmessage=async e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='response'&&m.payload?.pairingType==='PROMPT'){onPrompt&&onPrompt();return}if(m.type==='registered'){clearTimeout(to);this.ck=m.payload?.clientKey||this.ck;try{let r=await this.req('ssap://com.webos.service.networkinput/getPointerInputSocket');if(r.socketPath)this.ptr=new WebSocket(r.socketPath.startsWith('ws')?r.socketPath:`ws://${this.ip}:3000${r.socketPath}`)}catch{}ok(this.ck)}if(m.type==='response'||m.type==='error'){let p=this.pending.get(m.id);if(!p)return;this.pending.delete(m.id);m.type==='error'||m.payload?.returnValue===false?p[1](Error(m.error||m.payload?.errorText||'SSAP error')):p[0](m.payload||{})}};w.onerror=()=>{clearTimeout(to);bad(Error('Не удалось подключиться к ТВ — проверьте IP и что телефон в той же Wi‑Fi сети'))};w.onclose=()=>{clearTimeout(to)}})}req(uri,payload={}){return new Promise((r,j)=>{if(!this.ws||this.ws.readyState!==1)return j(Error('ТВ не подключён'));let i=key();this.pending.set(i,[r,j]);this.ws.send(JSON.stringify({type:'request',id:i,uri,payload}));setTimeout(()=>{if(this.pending.has(i)){this.pending.delete(i);j(Error('SSAP timeout'))}},10000)})}button(n){if(this.ptr?.readyState===1)this.ptr.send(`type:button\nname:${n}\n\n`)}move(dx,dy){if(this.ptr?.readyState===1)this.ptr.send(`type:move\ndx:${Math.round(dx)}\ndy:${Math.round(dy)}\ndown:0\n\n`)}click(){if(this.ptr?.readyState===1)this.ptr.send('type:click\n\n')}volume(v){return this.req('ssap://audio/setVolume',{volume:v})}mute(v){return this.req('ssap://audio/setMute',{mute:v})}text(v){return this.req('ssap://com.webos.service.ime/insertText',{text:v,replace:false})}enter(){return this.req('ssap://com.webos.service.ime/sendEnterKey')}channel(v){return this.req('ssap://tv/openChannel',{channelId:v})}powerOff(){return this.req('ssap://system/turnOff')}liveTV(){return this.req('ssap://system.launcher/launch',{id:'com.webos.app.livetv'})}close(){try{this.ptr?.close();this.ws?.close()}catch{}}}
function B(p){return <button {...p} className={'b '+(p.className||'')}/>}
function Connect({onConnect,status,err}){let[ip,setIp]=useState('');let busy=status==='connecting'||status==='prompt';return <div className="connect"><h1><Tv/> LG Web Remote</h1><p>Введите IP-адрес LG TV.</p><input value={ip}disabled={busy}onChange={e=>setIp(e.target.value)}placeholder="192.168.1.42"/><B className="primary full"disabled={busy}onClick={()=>!busy&&/^([0-9]{1,3}\.){3}[0-9]{1,3}$/.test(ip)&&onConnect({id:key(),name:'Мой LG',ip})}>{busy?'Подключаемся…':<><Plus/> Добавить ТВ</>}</B>{status==='prompt'&&<div className="notice">Проверьте экран телевизора — там должен появиться запрос на подключение. Подтвердите его пультом от ТВ.</div>}{status==='error'&&<div className="notice err">{err}</div>}<small>Телефон и ТВ должны быть в одной Wi‑Fi сети.</small></div>}
function Remote({c}){let[m,setM]=useState(false),[v,setV]=useState(40);let backLP=useLongPress(()=>c?.button('BACK'),()=>c?.liveTV());let homeLP=useLongPress(()=>c?.button('HOME'),()=>c?.powerOff());let pad=useTouchpad(c);return <div className="screen"><div className="pad"{...pad}><MousePointer2/><span className="padHint">Проведите пальцем — курсор. Тап — клик.</span></div><div className="actions"><B {...backLP}><ChevronLeft/></B><B {...homeLP}><Home/></B><B onClick={()=>{setM(!m);c?.mute(!m)}}>{m?<VolumeX/>:<Volume1/>}</B></div><div className="slider"><Volume1/><input type="range"min="0"max="100"value={v}onChange={e=>{let x=+e.target.value;setV(x);c?.volume(x)}}/><Volume2/></div></div>}
function Keys({c}){let[l,setL]=useState('RU'),[t,setT]=useState(''),rows=l==='RU'?RU:EN;let press=k=>k==='⌫'?setT(x=>x.slice(0,-1)):setT(x=>x+k);return <div className="screen"><div className="between"><b>Клавиатура</b><div className="seg">{['RU','EN'].map(x=><button className={l===x?'on':''}onClick={()=>setL(x)}>{x}</button>)}</div></div><div className="preview">{t||'Введите текст…'}</div>{rows.map(r=><div className="keyrow">{r.map(k=><B onClick={()=>press(k)}>{k}</B>)}</div>)}<div className="keyrow"><B onClick={()=>setL(l==='RU'?'EN':'RU')}>{l==='RU'?'EN':'RU'}</B><B className="space"onClick={()=>setT(t+' ')}>пробел</B><B onClick={()=>setT('')}>Clear</B></div><B className="primary full"onClick={()=>c?.text(t).then(()=>c.enter())}><Send/> Отправить</B></div>}
function Numbers({c}){let[n,setN]=useState('');let add=x=>setN(v=>(v+x).slice(0,3));return <div className="screen"><b>Номер канала</b><div className="display">{n||'—'}</div><div className="grid">{['1','2','3','4','5','6','7','8','9'].map(x=><B onClick={()=>add(x)}>{x}</B>)}<B onClick={()=>setN('')}>Clear</B><B onClick={()=>add('0')}>0</B><B className="primary"onClick={()=>n&&c?.channel(n)}><Check/></B></div></div>}
function Tabs({tab,setTab}){return <nav>{[['r',MousePointer2,'Пульт'],['k',Keyboard,'Клавиатура'],['n',Hash,'Цифры']].map(([id,I,s])=><button className={tab===id?'sel':''}onClick={()=>setTab(id)}><I/><span>{s}</span></button>)}</nav>}
export default function App(){let[tv,setTv]=useState(null),[c,setC]=useState(null),[tab,setTab]=useState('r'),[status,setStatus]=useState('idle'),[err,setErr]=useState(''),[online,setOnline]=useState(false);
let attempt=async x=>{setStatus('connecting');setErr('');let q=new LG(x.ip,x.clientKey);try{let ck=await q.connect(()=>setStatus('prompt'));x.clientKey=ck;localStorage.setItem('lg-tv',JSON.stringify(x));setTv(x);setC(q);setStatus('ok');setOnline(true)}catch(e){q.close();setStatus('error');setErr(e.message||'Не удалось подключиться')}};
useEffect(()=>{if(!c)return;let t=setInterval(()=>setOnline(c.ws?.readyState===1),1000);return()=>clearInterval(t)},[c]);
if(!tv||status!=='ok')return <Connect status={status}err={err}onConnect={attempt}/>;
return <div className="app"><header><div><small><span className={'dot '+(online?'on':'off')}/>{online?'Подключено':'Нет связи с ТВ'}</small><b>{tv.name}</b></div><button onClick={()=>{c?.close();setTv(null);setC(null);setStatus('idle')}}><X/></button></header>{!online&&<div className="banner">ТВ не отвечает.<button onClick={()=>attempt(tv)}>Переподключиться</button></div>}<main>{tab==='r'?<Remote c={c}/>:tab==='k'?<Keys c={c}/>:<Numbers c={c}/>}</main><Tabs tab={tab}setTab={setTab}/></div>}
createRoot(document.getElementById('root')).render(<App/>);
